// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChlIH2mYGk8BX-1wuVjsxsi6TFyDI62U8',
    appId: '1:377444611182:web:e164c2bf24d2d50013227f',
    messagingSenderId: '377444611182',
    projectId: 'weather-auth-7f92d',
    authDomain: 'weather-auth-7f92d.firebaseapp.com',
    storageBucket: 'weather-auth-7f92d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAchk9MePcHX6LnOQDWQ-XRYPGQ9b3H2Eo',
    appId: '1:377444611182:android:c84e47dcc011fa5513227f',
    messagingSenderId: '377444611182',
    projectId: 'weather-auth-7f92d',
    storageBucket: 'weather-auth-7f92d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyyuKxLIqim0ea5PBUbqj2hiqOQXZImQg',
    appId: '1:377444611182:ios:2f00e108e313c23c13227f',
    messagingSenderId: '377444611182',
    projectId: 'weather-auth-7f92d',
    storageBucket: 'weather-auth-7f92d.appspot.com',
    iosBundleId: 'com.example.weatherAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyyuKxLIqim0ea5PBUbqj2hiqOQXZImQg',
    appId: '1:377444611182:ios:84baca6a8addcb2713227f',
    messagingSenderId: '377444611182',
    projectId: 'weather-auth-7f92d',
    storageBucket: 'weather-auth-7f92d.appspot.com',
    iosBundleId: 'com.example.weatherAssignment.RunnerTests',
  );
}
